apiVersion: v1
kind: Service
metadata:
  name: cat-svc
spec:
  selector:
    app: cat
  type: NodePort
  ports:
    - protocol: TCP
      name: http-port
      port: 80
      targetPort: 8080
      nodePort: 31901