apiVersion: v1
kind: Service
metadata:
  name: monkey-svc
spec:
  selector:
    app: monkey
  internalTrafficPolicy: Cluster
  ports:
    - protocol: TCP
      name: http-port
      port: 80
      targetPort: 8080