apiVersion: v1
kind: Service
metadata:
  name: dog-svc
spec:
  selector:
    app: dog
  internalTrafficPolicy: Cluster
  ports:
    - protocol: TCP
      name: http-port
      port: 80
      targetPort: 8080