apiVersion: apps/v1
kind: Deployment
metadata:
  name: cat-dp-gray
  annotations:
    author: catface996
spec:
  selector:
    matchLabels:
      app: cat
      env: gray
  replicas: 2
  template:
    metadata:
      labels:
        app: cat
        env: gray
    spec:
      containers:
        - name: cat-ct-gray
          image: catface996/spring-cloud-istio-demo:latest
          ports:
            - containerPort: 9001
              protocol: TCP
