apiVersion: apps/v1
kind: Deployment
metadata:
  name: monkey-dp
spec:
  selector:
    matchLabels:
      app: monkey
      env: gray
      tier: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: monkey
        env: gray
        tier: frontend
    spec:
      containers:
        - name: monkey-ct
          image: catface996/spring-cloud-istio-demo:latest
          ports:
            - containerPort: 9001
              protocol: TCP
