apiVersion: apps/v1
kind: Deployment
metadata:
  name: dog-dp
  annotations:
    author: catface996
spec:
  selector:
    matchLabels:
      app: dog
      env: prod
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: dog
        env: prod
        tier: backend
    spec:
      containers:
        - name: dog-ct
          image: catface996/spring-cloud-istio-demo:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
          - name: SPRING_OPTS
            value: --spring.application.name=cat --server.port=8080 --env=gray --next=false --service.url=http://monkey-svc
          - name: JAVA_OPTS
            value: -Xmx512M -Xms512M
          resources:
            requests:
              cpu: "100m"
              memory: "512Mi"
            limits:
              cpu: "200m"
              memory: "1024Mi"
